Repository yeasy/docker_practice, pull requests merged in 2018-09, with the labels that each got.

#357 fix typo
  kubernetes/intro.md
Labels: spelling

#358 fix typos
  advanced_network/config_file.md
  kubernetes/quickstart.md
Labels: bug, spelling

#359 添加环境变量
  etcd/install.md
Labels: etcd
